### ISSUE TITLE
Fails to install on Python 3.10 due to pinned onnxruntime dependency

### ISSUE THREAD

**Issue by iksnagreb** [fastmachinelearning/qonnx#57] opened 2023-05-24 14:27 UTC
## Prerequisites
Please make sure to check off these prerequisites before submitting a bug report.
- [x] Test that the bug appears on the current version of the main branch. Make sure to include the commit hash of the commit you checked out.
- [x] Check that the issue hasn't already been reported, by checking the currently open issues.
- [x] If there are steps to reproduce the problem, make sure to write them down below.
- [x] If relevant, please include the ONNX files, which were created directly before and/or after the bug.

## Quick summary
Installing qonnx via pip on python 3.10 fails due to the pinned onnxruntime==1.11.1 dependency being no longer available. This happens for the most recent release on PyPI as well as for the current state of the main branch.

### Steps to Reproduce
On python 3.10 running `pip install qonnx` yields the following error message, this is similar for installing from the current main branch:

```
...
ERROR: Cannot install qonnx==0.1 and qonnx==0.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    qonnx 0.2.0 depends on onnxruntime==1.11.1
    qonnx 0.1 depends on onnxruntime==1.11.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### Expected behavior
It should be possible to install qonnx on python 3.10 (after solving this dependency issue), especially as this is the default python version on Ubuntu 22.04, which is probably a common choice of operating system.

### Actual behavior
Installing via pip fails resolving the dependencies.

### Possible fix
Pinning the onnxruntime dependency to a more recent version, potentially to the most recent release 1.15.0 should solve the problem without introducing any major issues. I am already testing this and will be happy to contribute a pull request.

**Comment by fpjentzsch** [comment] 2023-05-25 10:54
Hi,
updating onnxruntime will also be required for the planned FINN update to Python 3.10 (see https://github.com/Xilinx/finn/pull/824).

**Comment by maltanar** [comment] 2023-06-08 08:12
#58 is now merged, and it seems to me that the issue is resolved. Can you confirm?

**Closed** 2023-06-08 09:31 UTC
Labels: bug
